// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"

	ovsdb "github.com/ovn-org/libovsdb/ovsdb"
)

// AddressSetIPs is an autogenerated mock type for the AddressSetIPs type
type AddressSetIPs struct {
	mock.Mock
}

// AddIPs provides a mock function with given fields: ip
func (_m *AddressSetIPs) AddIPs(ip []net.IP) error {
	ret := _m.Called(ip)

	var r0 error
	if rf, ok := ret.Get(0).(func([]net.IP) error); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddIPsReturnOps provides a mock function with given fields: ip
func (_m *AddressSetIPs) AddIPsReturnOps(ip []net.IP) ([]ovsdb.Operation, error) {
	ret := _m.Called(ip)

	var r0 []ovsdb.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func([]net.IP) ([]ovsdb.Operation, error)); ok {
		return rf(ip)
	}
	if rf, ok := ret.Get(0).(func([]net.IP) []ovsdb.Operation); ok {
		r0 = rf(ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ovsdb.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func([]net.IP) error); ok {
		r1 = rf(ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteIPs provides a mock function with given fields: ip
func (_m *AddressSetIPs) DeleteIPs(ip []net.IP) error {
	ret := _m.Called(ip)

	var r0 error
	if rf, ok := ret.Get(0).(func([]net.IP) error); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteIPsReturnOps provides a mock function with given fields: ip
func (_m *AddressSetIPs) DeleteIPsReturnOps(ip []net.IP) ([]ovsdb.Operation, error) {
	ret := _m.Called(ip)

	var r0 []ovsdb.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func([]net.IP) ([]ovsdb.Operation, error)); ok {
		return rf(ip)
	}
	if rf, ok := ret.Get(0).(func([]net.IP) []ovsdb.Operation); ok {
		r0 = rf(ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ovsdb.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func([]net.IP) error); ok {
		r1 = rf(ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Destroy provides a mock function with given fields:
func (_m *AddressSetIPs) Destroy() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetASHashNames provides a mock function with given fields:
func (_m *AddressSetIPs) GetASHashNames() (string, string) {
	ret := _m.Called()

	var r0 string
	var r1 string
	if rf, ok := ret.Get(0).(func() (string, string)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// GetIPs provides a mock function with given fields:
func (_m *AddressSetIPs) GetIPs() ([]string, []string) {
	ret := _m.Called()

	var r0 []string
	var r1 []string
	if rf, ok := ret.Get(0).(func() ([]string, []string)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() []string); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	return r0, r1
}

// GetName provides a mock function with given fields:
func (_m *AddressSetIPs) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetIPs provides a mock function with given fields: ip
func (_m *AddressSetIPs) SetIPs(ip []net.IP) error {
	ret := _m.Called(ip)

	var r0 error
	if rf, ok := ret.Get(0).(func([]net.IP) error); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAddressSetIPs interface {
	mock.TestingT
	Cleanup(func())
}

// NewAddressSetIPs creates a new instance of AddressSetIPs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAddressSetIPs(t mockConstructorTestingTNewAddressSetIPs) *AddressSetIPs {
	mock := &AddressSetIPs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
