// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	ops "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/libovsdb/ops"
	mock "github.com/stretchr/testify/mock"
)

// AddressSetIterFunc is an autogenerated mock type for the AddressSetIterFunc type
type AddressSetIterFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: dbIDs
func (_m *AddressSetIterFunc) Execute(dbIDs *ops.DbObjectIDs) error {
	ret := _m.Called(dbIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ops.DbObjectIDs) error); ok {
		r0 = rf(dbIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAddressSetIterFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewAddressSetIterFunc creates a new instance of AddressSetIterFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAddressSetIterFunc(t mockConstructorTestingTNewAddressSetIterFunc) *AddressSetIterFunc {
	mock := &AddressSetIterFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
