// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	addressset "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/address_set"
	mock "github.com/stretchr/testify/mock"

	net "net"

	ops "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/libovsdb/ops"

	ovsdb "github.com/ovn-org/libovsdb/ovsdb"
)

// AddressSetFactoryCIDRs is an autogenerated mock type for the AddressSetFactoryCIDRs type
type AddressSetFactoryCIDRs struct {
	mock.Mock
}

// DestroyAddressSet provides a mock function with given fields: dbIDs
func (_m *AddressSetFactoryCIDRs) DestroyAddressSet(dbIDs *ops.DbObjectIDs) error {
	ret := _m.Called(dbIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ops.DbObjectIDs) error); ok {
		r0 = rf(dbIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureAddressSet provides a mock function with given fields: dbIDs
func (_m *AddressSetFactoryCIDRs) EnsureAddressSet(dbIDs *ops.DbObjectIDs) (addressset.AddressSetCIDRs, error) {
	ret := _m.Called(dbIDs)

	var r0 addressset.AddressSetCIDRs
	var r1 error
	if rf, ok := ret.Get(0).(func(*ops.DbObjectIDs) (addressset.AddressSetCIDRs, error)); ok {
		return rf(dbIDs)
	}
	if rf, ok := ret.Get(0).(func(*ops.DbObjectIDs) addressset.AddressSetCIDRs); ok {
		r0 = rf(dbIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(addressset.AddressSetCIDRs)
		}
	}

	if rf, ok := ret.Get(1).(func(*ops.DbObjectIDs) error); ok {
		r1 = rf(dbIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAddressSet provides a mock function with given fields: dbIDs
func (_m *AddressSetFactoryCIDRs) GetAddressSet(dbIDs *ops.DbObjectIDs) (addressset.AddressSetCIDRs, error) {
	ret := _m.Called(dbIDs)

	var r0 addressset.AddressSetCIDRs
	var r1 error
	if rf, ok := ret.Get(0).(func(*ops.DbObjectIDs) (addressset.AddressSetCIDRs, error)); ok {
		return rf(dbIDs)
	}
	if rf, ok := ret.Get(0).(func(*ops.DbObjectIDs) addressset.AddressSetCIDRs); ok {
		r0 = rf(dbIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(addressset.AddressSetCIDRs)
		}
	}

	if rf, ok := ret.Get(1).(func(*ops.DbObjectIDs) error); ok {
		r1 = rf(dbIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAddressSet provides a mock function with given fields: dbIDs, cidrs
func (_m *AddressSetFactoryCIDRs) NewAddressSet(dbIDs *ops.DbObjectIDs, cidrs []*net.IPNet) (addressset.AddressSetCIDRs, error) {
	ret := _m.Called(dbIDs, cidrs)

	var r0 addressset.AddressSetCIDRs
	var r1 error
	if rf, ok := ret.Get(0).(func(*ops.DbObjectIDs, []*net.IPNet) (addressset.AddressSetCIDRs, error)); ok {
		return rf(dbIDs, cidrs)
	}
	if rf, ok := ret.Get(0).(func(*ops.DbObjectIDs, []*net.IPNet) addressset.AddressSetCIDRs); ok {
		r0 = rf(dbIDs, cidrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(addressset.AddressSetCIDRs)
		}
	}

	if rf, ok := ret.Get(1).(func(*ops.DbObjectIDs, []*net.IPNet) error); ok {
		r1 = rf(dbIDs, cidrs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAddressSetOps provides a mock function with given fields: dbIDs, cidrs
func (_m *AddressSetFactoryCIDRs) NewAddressSetOps(dbIDs *ops.DbObjectIDs, cidrs []*net.IPNet) (addressset.AddressSetCIDRs, []ovsdb.Operation, error) {
	ret := _m.Called(dbIDs, cidrs)

	var r0 addressset.AddressSetCIDRs
	var r1 []ovsdb.Operation
	var r2 error
	if rf, ok := ret.Get(0).(func(*ops.DbObjectIDs, []*net.IPNet) (addressset.AddressSetCIDRs, []ovsdb.Operation, error)); ok {
		return rf(dbIDs, cidrs)
	}
	if rf, ok := ret.Get(0).(func(*ops.DbObjectIDs, []*net.IPNet) addressset.AddressSetCIDRs); ok {
		r0 = rf(dbIDs, cidrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(addressset.AddressSetCIDRs)
		}
	}

	if rf, ok := ret.Get(1).(func(*ops.DbObjectIDs, []*net.IPNet) []ovsdb.Operation); ok {
		r1 = rf(dbIDs, cidrs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]ovsdb.Operation)
		}
	}

	if rf, ok := ret.Get(2).(func(*ops.DbObjectIDs, []*net.IPNet) error); ok {
		r2 = rf(dbIDs, cidrs)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProcessEachAddressSet provides a mock function with given fields: ownerController, dbIDsType, iteratorFn
func (_m *AddressSetFactoryCIDRs) ProcessEachAddressSet(ownerController string, dbIDsType *ops.ObjectIDsType, iteratorFn addressset.AddressSetIterFunc) error {
	ret := _m.Called(ownerController, dbIDsType, iteratorFn)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *ops.ObjectIDsType, addressset.AddressSetIterFunc) error); ok {
		r0 = rf(ownerController, dbIDsType, iteratorFn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAddressSetFactoryCIDRs interface {
	mock.TestingT
	Cleanup(func())
}

// NewAddressSetFactoryCIDRs creates a new instance of AddressSetFactoryCIDRs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAddressSetFactoryCIDRs(t mockConstructorTestingTNewAddressSetFactoryCIDRs) *AddressSetFactoryCIDRs {
	mock := &AddressSetFactoryCIDRs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
