/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressip/v1"
	egressipv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressip/v1/apis/applyconfiguration/egressip/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEgressIPTraffics implements EgressIPTrafficInterface
type FakeEgressIPTraffics struct {
	Fake *FakeK8sV1
}

var egressiptrafficsResource = v1.SchemeGroupVersion.WithResource("egressiptraffics")

var egressiptrafficsKind = v1.SchemeGroupVersion.WithKind("EgressIPTraffic")

// Get takes name of the egressIPTraffic, and returns the corresponding egressIPTraffic object, and an error if there is any.
func (c *FakeEgressIPTraffics) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EgressIPTraffic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(egressiptrafficsResource, name), &v1.EgressIPTraffic{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EgressIPTraffic), err
}

// List takes label and field selectors, and returns the list of EgressIPTraffics that match those selectors.
func (c *FakeEgressIPTraffics) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EgressIPTrafficList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(egressiptrafficsResource, egressiptrafficsKind, opts), &v1.EgressIPTrafficList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.EgressIPTrafficList{ListMeta: obj.(*v1.EgressIPTrafficList).ListMeta}
	for _, item := range obj.(*v1.EgressIPTrafficList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested egressIPTraffics.
func (c *FakeEgressIPTraffics) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(egressiptrafficsResource, opts))
}

// Create takes the representation of a egressIPTraffic and creates it.  Returns the server's representation of the egressIPTraffic, and an error, if there is any.
func (c *FakeEgressIPTraffics) Create(ctx context.Context, egressIPTraffic *v1.EgressIPTraffic, opts metav1.CreateOptions) (result *v1.EgressIPTraffic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(egressiptrafficsResource, egressIPTraffic), &v1.EgressIPTraffic{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EgressIPTraffic), err
}

// Update takes the representation of a egressIPTraffic and updates it. Returns the server's representation of the egressIPTraffic, and an error, if there is any.
func (c *FakeEgressIPTraffics) Update(ctx context.Context, egressIPTraffic *v1.EgressIPTraffic, opts metav1.UpdateOptions) (result *v1.EgressIPTraffic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(egressiptrafficsResource, egressIPTraffic), &v1.EgressIPTraffic{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EgressIPTraffic), err
}

// Delete takes name of the egressIPTraffic and deletes it. Returns an error if one occurs.
func (c *FakeEgressIPTraffics) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(egressiptrafficsResource, name, opts), &v1.EgressIPTraffic{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEgressIPTraffics) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(egressiptrafficsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.EgressIPTrafficList{})
	return err
}

// Patch applies the patch and returns the patched egressIPTraffic.
func (c *FakeEgressIPTraffics) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressIPTraffic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(egressiptrafficsResource, name, pt, data, subresources...), &v1.EgressIPTraffic{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EgressIPTraffic), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied egressIPTraffic.
func (c *FakeEgressIPTraffics) Apply(ctx context.Context, egressIPTraffic *egressipv1.EgressIPTrafficApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EgressIPTraffic, err error) {
	if egressIPTraffic == nil {
		return nil, fmt.Errorf("egressIPTraffic provided to Apply must not be nil")
	}
	data, err := json.Marshal(egressIPTraffic)
	if err != nil {
		return nil, err
	}
	name := egressIPTraffic.Name
	if name == nil {
		return nil, fmt.Errorf("egressIPTraffic.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(egressiptrafficsResource, *name, types.ApplyPatchType, data), &v1.EgressIPTraffic{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.EgressIPTraffic), err
}
