/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressip/v1"
	egressipv1 "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressip/v1/apis/applyconfiguration/egressip/v1"
	scheme "github.com/ovn-org/ovn-kubernetes/go-controller/pkg/crd/egressip/v1/apis/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EgressIPTrafficsGetter has a method to return a EgressIPTrafficInterface.
// A group's client should implement this interface.
type EgressIPTrafficsGetter interface {
	EgressIPTraffics() EgressIPTrafficInterface
}

// EgressIPTrafficInterface has methods to work with EgressIPTraffic resources.
type EgressIPTrafficInterface interface {
	Create(ctx context.Context, egressIPTraffic *v1.EgressIPTraffic, opts metav1.CreateOptions) (*v1.EgressIPTraffic, error)
	Update(ctx context.Context, egressIPTraffic *v1.EgressIPTraffic, opts metav1.UpdateOptions) (*v1.EgressIPTraffic, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.EgressIPTraffic, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EgressIPTrafficList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressIPTraffic, err error)
	Apply(ctx context.Context, egressIPTraffic *egressipv1.EgressIPTrafficApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EgressIPTraffic, err error)
	EgressIPTrafficExpansion
}

// egressIPTraffics implements EgressIPTrafficInterface
type egressIPTraffics struct {
	client rest.Interface
}

// newEgressIPTraffics returns a EgressIPTraffics
func newEgressIPTraffics(c *K8sV1Client) *egressIPTraffics {
	return &egressIPTraffics{
		client: c.RESTClient(),
	}
}

// Get takes name of the egressIPTraffic, and returns the corresponding egressIPTraffic object, and an error if there is any.
func (c *egressIPTraffics) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EgressIPTraffic, err error) {
	result = &v1.EgressIPTraffic{}
	err = c.client.Get().
		Resource("egressiptraffics").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EgressIPTraffics that match those selectors.
func (c *egressIPTraffics) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EgressIPTrafficList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EgressIPTrafficList{}
	err = c.client.Get().
		Resource("egressiptraffics").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested egressIPTraffics.
func (c *egressIPTraffics) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("egressiptraffics").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a egressIPTraffic and creates it.  Returns the server's representation of the egressIPTraffic, and an error, if there is any.
func (c *egressIPTraffics) Create(ctx context.Context, egressIPTraffic *v1.EgressIPTraffic, opts metav1.CreateOptions) (result *v1.EgressIPTraffic, err error) {
	result = &v1.EgressIPTraffic{}
	err = c.client.Post().
		Resource("egressiptraffics").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressIPTraffic).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a egressIPTraffic and updates it. Returns the server's representation of the egressIPTraffic, and an error, if there is any.
func (c *egressIPTraffics) Update(ctx context.Context, egressIPTraffic *v1.EgressIPTraffic, opts metav1.UpdateOptions) (result *v1.EgressIPTraffic, err error) {
	result = &v1.EgressIPTraffic{}
	err = c.client.Put().
		Resource("egressiptraffics").
		Name(egressIPTraffic.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(egressIPTraffic).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the egressIPTraffic and deletes it. Returns an error if one occurs.
func (c *egressIPTraffics) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("egressiptraffics").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *egressIPTraffics) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("egressiptraffics").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched egressIPTraffic.
func (c *egressIPTraffics) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EgressIPTraffic, err error) {
	result = &v1.EgressIPTraffic{}
	err = c.client.Patch(pt).
		Resource("egressiptraffics").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied egressIPTraffic.
func (c *egressIPTraffics) Apply(ctx context.Context, egressIPTraffic *egressipv1.EgressIPTrafficApplyConfiguration, opts metav1.ApplyOptions) (result *v1.EgressIPTraffic, err error) {
	if egressIPTraffic == nil {
		return nil, fmt.Errorf("egressIPTraffic provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(egressIPTraffic)
	if err != nil {
		return nil, err
	}
	name := egressIPTraffic.Name
	if name == nil {
		return nil, fmt.Errorf("egressIPTraffic.Name must be provided to Apply")
	}
	result = &v1.EgressIPTraffic{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("egressiptraffics").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
